task number 26
SkoltechSummerCamp/leetcode pull request #8
Opened 2022-07-26 10:12 UTC by Ch1pchilinka

2022-07-26 13:34 UTC, crazydiver requested changes
Кодстайл: разбивать программу на логические блоки пустыми строками

2022-07-26 13:34 UTC, crazydiver commented on Ch1pchilinka/122. Best Time to Buy and Sell Stock II/main.cpp
> +      bool flag = true;
Непонятное название переменной

2022-07-26 13:34 UTC, crazydiver commented on Ch1pchilinka/122. Best Time to Buy and Sell Stock II/main.cpp
> +      int n = prices.size(), profit = 0, buy = 0;
Непонятное название переменной + встречается в другой функции
Неверный тип данных

2022-07-26 13:51 UTC, AdvancerMan requested changes

2022-07-26 13:51 UTC, AdvancerMan commented on Ch1pchilinka/136. Single Number/main.cpp
> +      for (auto & el : nums) {
Лучше не использовать авто-типизацию

2022-07-26 13:51 UTC, AdvancerMan commented on Ch1pchilinka/189. Rotate Array/main.cpp
> +    int n = static_cast<int>(nums.size());
Если использовать правильный тип данных, кастить необязательно. 
ПС. Кастить плохо, если его можно избежать (длительная операция)

2022-07-26 13:51 UTC, AdvancerMan commented on Ch1pchilinka/189. Rotate Array/main.cpp
> +  std::cout << "\n";
Изучи разницу между \n и endl. Можно писать и так и так, но тут лучше бы выглядел endl

2022-07-26 13:51 UTC, AdvancerMan commented on Ch1pchilinka/217. Contains Duplicate/main.cpp
> +    int n = nums.size();
Неверный тип данных

2022-07-26 13:51 UTC, AdvancerMan commented on Ch1pchilinka/217. Contains Duplicate/main.cpp
> +    std::sort(nums.begin(), nums.end(), std::greater());
Зачем 3-й аргумент?

2022-07-26 13:51 UTC, AdvancerMan commented on Ch1pchilinka/26. Remove Duplicates from Sorted Array /main.cpp
> +  for (int i = 0; i < n; ++i) {
Неверный тип данных

2022-07-26 13:51 UTC, AdvancerMan commented on Ch1pchilinka/26. Remove Duplicates from Sorted Array /main.cpp
> +  for (int i = 0; i < n; ++i) {
Неверный тип данных

2022-07-26 19:02 UTC, Ch1pchilinka commented on Ch1pchilinka/26. Remove Duplicates from Sorted Array /main.cpp
> +  for (int i = 0; i < n; ++i) {
Можно поподробнее, я что-то не понимаю

2022-07-26 19:03 UTC, Ch1pchilinka commented on Ch1pchilinka/26. Remove Duplicates from Sorted Array /main.cpp
> +  for (int i = 0; i < n; ++i) {
И тут тоже

2022-07-26 19:08 UTC, Ch1pchilinka commented on Ch1pchilinka/122. Best Time to Buy and Sell Stock II/main.cpp
> +      bool flag = true;
flag вроде стандартная для bool?

2022-07-26 19:10 UTC, Ch1pchilinka commented on Ch1pchilinka/122. Best Time to Buy and Sell Stock II/main.cpp
> +      int n = prices.size(), profit = 0, buy = 0;
Вроде названия говорящие и функция (кроме main) одна только. Про тип данных опять не понял.

2022-07-26 19:15 UTC, Ch1pchilinka commented on Ch1pchilinka/136. Single Number/main.cpp
> +      for (auto & el : nums) {
А как же правило AAA?

2022-07-27 09:12 UTC, merged

2022-07-27 10:00 UTC, crazydiver commented on Ch1pchilinka/122. Best Time to Buy and Sell Stock II/main.cpp
> +      bool flag = true;
Когда ставишь флаги лучше называть его по смыслу флага, например, если тебе нужен флаг проверки на то, является ли сивол цифрой, пишешь isDigit, а не flag